// checklists.js
export const CHECKLISTS = [
   {
    key: "mcfarland_psc",
    name: "McFarland Public Safety Center",
    location: "Fire Alarm Device Inspection",
    devices: [
      { loop: 1, address: 1, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939747909', messages: 'BASEMENT SMOKE ABOVE FACP' },
      { loop: 1, address: 2, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3831067556', messages: 'BASEMENT HEAT BY SPRINK PIPING' },
      { loop: 1, address: 3, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828858723', messages: 'BASEMENT HEAT MECHANICAL RM' },
      { loop: 1, address: 4, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754204', messages: 'BASEMENT SMOKE ELEVATOR SMOKE' },
      { loop: 1, address: 5, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828858570', messages: 'BASEMENT HEAT OUTSIDE PANEL RM' },
      { loop: 1, address: 6, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828849349', messages: 'BASEMENT HEAT ABOVE PANEL' },
      { loop: 1, address: 7, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828845501', messages: 'BASEMENT HEAT MIDDLE/STAIRWELL B' },
      { loop: 1, address: 8, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828862416', messages: 'BASEMENT HEAT FAR MIDDLE/STAIR A' },
      { loop: 1, address: 9, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828845457', messages: 'BASEMENT HEAT NORTH/STAIRWELL A' },
      { loop: 1, address: 10, model: 'SD', deviceType: 'Duct Supervisory Latching', serialNumber: '3969261901', messages: 'APPATURE BAY MEZ DUCT DETECTOR' },
      { loop: 1, address: 11, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939777975', messages: 'PENTHOUSE SMOKE ABOVE BOSCH DIALER' },
      { loop: 1, address: 12, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754365', messages: 'SOUTH STAIRWELL SMOKE DETECTOR' },
      { loop: 1, address: 13, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939647735', messages: 'OUTSIDE SOUTH STAIR NEXT TO EXTERIOR DR' },
      { loop: 1, address: 14, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753535', messages: '1ST FLOOR SMOKE CORRIDOR TO STAIR B' },
      { loop: 1, address: 15, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753511', messages: '1ST FLOOR SMOKE S/E APP BAY' },
      { loop: 1, address: 16, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754167', messages: '1ST FLOOR SMOKE ELEVATOR SMOKE' },
      { loop: 1, address: 17, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939755119', messages: '1ST FLOOR SMOKE OUTSIDE ELEVATOR' },
      { loop: 1, address: 18, model: 'SD', deviceType: 'Duct Supervisory Latching', serialNumber: '3912816448', messages: '1ST FLOOR DUCT STAIRWELL B' },
      { loop: 1, address: 19, model: 'SD', deviceType: 'Duct Supervisory Latching', serialNumber: '3912816295', messages: '1ST FLOOR DUCT STAIRWELL B' },
      { loop: 1, address: 20, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754259', messages: '1ST FLOOR SMOKE EAST APP BAY' },
      { loop: 1, address: 21, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754297', messages: '1ST FLOOR SMOKE TRAINING STORAGE' },
      { loop: 1, address: 22, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939755096', messages: '1ST FLOOR SMOKE MEDICAL STORAGE' },
      { loop: 1, address: 23, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939755225', messages: '1ST FLOOR SMOKE IT/COMM ROOM' },
      { loop: 1, address: 24, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754020', messages: '1ST FLOOR SMOKE JANITOR STORAGE' },
      { loop: 1, address: 25, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939747961', messages: '1ST FLOOR SMOKE AV STORAGE ROOM' },
      { loop: 1, address: 26, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754792', messages: '1ST FLOOR SMOKE COURT STORAGE' },
      { loop: 1, address: 27, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753962', messages: '1ST FLOOR POLICE SM EVIDENCE PROC. STOR.' },
      { loop: 1, address: 28, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753849', messages: '1ST FLOOR SMOKE POLICE IT CLOSET' },
      { loop: 1, address: 29, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753832', messages: '1ST FLOOR SMOKE POLICE SHOWER STRG' },
      { loop: 1, address: 30, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939759575', messages: '1ST FLOOR SMOKE POLICE INVEST RM' },
      { loop: 1, address: 31, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939758134', messages: '1ST FLOOR SMOKE POLICE P120 STORAGE' },
      { loop: 1, address: 32, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754921', messages: '1ST FLOOR SMOKE POLICE MECH RM' },
      { loop: 1, address: 33, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828859904', messages: '2ND FLOOR HEAT WEST MECH ROOM' },
      { loop: 1, address: 34, model: 'HRS', deviceType: 'Heat ROR', serialNumber: '3828858587', messages: '2ND FLOOR HEAT WEST MECH ROOM' },
      { loop: 1, address: 35, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939735654', messages: '2ND FLOOR SMOKE STIARWELL B' },
      { loop: 1, address: 36, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754563', messages: 'TOP OF ELEVATOR SHAFT SMOKE' },
      { loop: 1, address: 37, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754266', messages: '2ND FLOOR SMOKE OUTSIDE ELEVATOR' },
      { loop: 1, address: 38, model: 'HFS', deviceType: 'Heat', serialNumber: '3622616017', messages: 'TOP OF ELEVATOR SHAFT HEAT' },
      { loop: 1, address: 39, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939753870', messages: '2ND FLOOR SMOKE OUTSIDE DORM 12' },
      { loop: 1, address: 40, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939776800', messages: '2ND FLOOR SMOKE DORM 12' },
      { loop: 1, address: 41, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754525', messages: '2ND FLOOR SMOKE OUTSIDE DORM 11' },
      { loop: 1, address: 42, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939736088', messages: '2ND FLOOR SMOKE DORM 11' },
      { loop: 1, address: 43, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939754242', messages: '2ND FLOOR SMOKE DORM 10' },
      { loop: 1, address: 44, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939778194', messages: '2ND FLOOR SMOKE DORM 9' },
      { loop: 1, address: 45, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754945', messages: '2ND FLOOR SMOKE OUTSIDE DORM 8/9' },
      { loop: 1, address: 46, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939754938', messages: '2ND FLOOR SMOKE DORM 8' },
      { loop: 1, address: 47, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939754822', messages: '2ND FLOOR SMOKE DORM7' },
      { loop: 1, address: 48, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939754044', messages: '2ND FLOOR SMOKE DORM 6' },
      { loop: 1, address: 49, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939755102', messages: '2ND FLOOR SMOKE OUTSIDE DORM 5/6' },
      { loop: 1, address: 50, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939747923', messages: '2ND FLOOR SMOKE DORM 5' },
      { loop: 1, address: 51, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939753894', messages: '2ND FLOOR SMOKE DORM 4' },
      { loop: 1, address: 52, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939755010', messages: '2ND FLOOR SMOKE OUTSIDE DORM 3/4' },
      { loop: 1, address: 53, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939753856', messages: '2ND FLOOR SMOKE DORM 3' },
      { loop: 1, address: 54, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939755065', messages: '2ND FLOOR SMOKE DORM 2' },
      { loop: 1, address: 55, model: 'PS', deviceType: 'Supervisory Non-Latching', serialNumber: '3939754433', messages: '2ND FLOOR SMOKE DORM 1' },
      { loop: 1, address: 56, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939754952', messages: '2ND FLOOR SMOKE OUTSIDE DORM 1' },
      { loop: 1, address: 57, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939747619', messages: '2ND FLOOR SMOKE NORTH STAIRWELL' },
      { loop: 1, address: 58, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3945817825', messages: '1ST FLOOR SMOKE ROLL DOWN DOOR' },
      { loop: 1, address: 60, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3934208757', messages: '1ST FLOOR SMOKE ROLL DOWN DOOR' },
      { loop: 1, address: 65, model: 'PS', deviceType: 'Smoke Verified', serialNumber: '3939758455', messages: 'SOUTH STAIRWELL ROOF ACCESS' },
      { loop: 1, address: 80, model: 'IM', deviceType: 'Monitor', serialNumber: '3698974301', messages: 'ISOLATOR MODULE BASEMENT FACP' },
      { loop: 1, address: 81, model: 'IM', deviceType: 'Monitor', serialNumber: '3698972574', messages: 'ISOLATOR MODULE 1ST FLOOR FACP' },
      { loop: 1, address: 82, model: 'IM', deviceType: 'Monitor', serialNumber: '3698973106', messages: 'ISOLATOR MODULE 2ND FLOOR FACP' },
      { loop: 1, address: 83, model: 'IM', deviceType: 'Monitor', serialNumber: '3698973830', messages: 'ISOLATOR MODULE 2ND FLR DORMS FACP' },
      { loop: 1, address: 126, model: '278', deviceType: 'Pull Station', serialNumber: '4899926137', messages: 'BASEMENT PULL STAIR B' },
      { loop: 1, address: 127, model: '278', deviceType: 'Pull Station', serialNumber: '4899926700', messages: '2ND FLOOR PULL APP. BAY STORAGE' },
      { loop: 1, address: 128, model: '278', deviceType: 'Pull Station', serialNumber: '4899925901', messages: 'BASEMENT PULL STAIRWELL A' },
      { loop: 1, address: 129, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4922818507', messages: 'ZONE #1 CONTROL VALVE ACTIVE' },
      { loop: 1, address: 130, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4922818514', messages: 'ZONE #2 CONTROL VALVE ACTIVE' },
      { loop: 1, address: 131, model: 'CT2', deviceType: 'Water Flow NoDelay', serialNumber: '4922828643', messages: 'ZONE #1 WATEFLOW ACTIVE' },
      { loop: 1, address: 132, model: 'CT2', deviceType: 'Water Flow NoDelay', serialNumber: '4922828650', messages: 'ZONE #2 WATERFLOW ACTIVE' },
      { loop: 1, address: 133, model: 'CT1', deviceType: 'Supervisory Non-Latching', serialNumber: '4800233804', messages: 'BASEMENT ELEV EQUIP POWER MONITOR' },
      { loop: 1, address: 134, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222515448', messages: 'BASEMENT ELEV EQUIP SHUNT TRIP' },
      { loop: 1, address: 135, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516698', messages: 'ELEVATOR MAIN RECALL' },
      { loop: 1, address: 136, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516971', messages: 'ELEVATOR SECONDARY RECALL' },
      { loop: 1, address: 137, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516896', messages: 'ELEVATOR HAT' },
      { loop: 1, address: 138, model: '278', deviceType: 'Pull Station', serialNumber: '4899919580', messages: '1ST FLOOR PULL S/W APP BAY EXIT' },
      { loop: 1, address: 139, model: '278', deviceType: 'Pull Station', serialNumber: '4899926144', messages: '1ST FLOOR PULL TURN-OUT GEAR EXIT' },
      { loop: 1, address: 140, model: '278', deviceType: 'Pull Station', serialNumber: '4899919313', messages: '1ST FLOOR PULL ANTIQUE BAY EXIT' },
      { loop: 1, address: 141, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516957', messages: '1ST FLOOR DUCT CR AHU SHUTDOWN STAIR B' },
      { loop: 1, address: 142, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516841', messages: '1ST FLOOR DUCT CR AHU SHUTDOWN STAIR B' },
      { loop: 1, address: 143, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4925797465', messages: 'DIALER TROUBLE PENTHOUSE BOSCH' },
      { loop: 1, address: 144, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5221949961', messages: 'AHU #3 SHUTDOWN' },
      { loop: 1, address: 145, model: '278', deviceType: 'Pull Station', serialNumber: '4899927172', messages: '1ST FLOOR PULL STAIRWELL B' },
      { loop: 1, address: 146, model: '278', deviceType: 'Pull Station', serialNumber: '4899919245', messages: '1ST FLOOR PULL STAIRWELL A' },
      { loop: 1, address: 147, model: '278', deviceType: 'Pull Station', serialNumber: '4899928186', messages: '1ST FLOOR PULL SOUTH VESTIBULE' },
      { loop: 1, address: 148, model: '278', deviceType: 'Pull Station', serialNumber: '4899928094', messages: '1ST FLOOR PULL COURT/TRAINING RM' },
      { loop: 1, address: 149, model: '278', deviceType: 'Pull Station', serialNumber: '4899927097', messages: '1ST FLOOR PULL OUTSIDE INTERVIEW RM' },
      { loop: 1, address: 150, model: '278', deviceType: 'Pull Station', serialNumber: '4899926434', messages: '1ST FLOOR PULL MAIN VESTIBULE' },
      { loop: 1, address: 151, model: '278', deviceType: 'Pull Station', serialNumber: '4899926304', messages: '1ST FLOOR PULL POLICE VESTIBULE' },
      { loop: 1, address: 152, model: '278', deviceType: 'Pull Station', serialNumber: '4899930905', messages: '1ST FLOOR PULL POLICE GARAGE 3/3' },
      { loop: 1, address: 153, model: '278', deviceType: 'Pull Station', serialNumber: '4899919788', messages: '1ST FLOOR PULL POLICE GARAGE 2/3' },
      { loop: 1, address: 154, model: '278', deviceType: 'Pull Station', serialNumber: '4899919849', messages: 'PENTHOUSE TO ROOF ACCESS' },
      { loop: 1, address: 155, model: '278', deviceType: 'Pull Station', serialNumber: '4899926717', messages: '2ND FLOOR PULL STAIRWELL B' },
      { loop: 1, address: 156, model: 'CT1', deviceType: 'Supervisory Non-Latching', serialNumber: '4800233392', messages: '2ND FLOOR RANGE HOOD NEED TO TEST' },
      { loop: 1, address: 157, model: '278', deviceType: 'Pull Station', serialNumber: '4899927875', messages: '2ND FLOOR PULL KITCHEN TO APP BAY' },
      { loop: 1, address: 158, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5221705154', messages: 'BASEMENT CR DOOR HOLDER' },
      { loop: 1, address: 159, model: '278', deviceType: 'Pull Station', serialNumber: '4899931070', messages: '2ND FLOOR PULL STAIRWELL A' },
      { loop: 1, address: 160, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4921144881', messages: 'BACK FLOW SECONDARY CONTROL VALVE ACTIVE' },
      { loop: 1, address: 161, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4921144898', messages: 'BACKFLOW PRIMARY CONTROL VALVE ACTIVE' },
      { loop: 1, address: 162, model: 'CT2', deviceType: 'Supervisory Non-Latching', serialNumber: '4925797472', messages: 'DIALER/NOT USED CT2 TO BOSCH CELL' },
      { loop: 1, address: 163, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5225324788', messages: 'TROUBLE TO BOSCH PENTHOUSE FIRE' },
      { loop: 1, address: 164, model: '278', deviceType: 'Pull Station', serialNumber: '4899918859', messages: '1ST FLOOR PULL POLICE GARAGE 1/3' },
      { loop: 1, address: 165, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5223936815', messages: 'PENTHOUSE FIRE ALARM TO BOSCH DIALER' },
      { loop: 1, address: 166, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222572595', messages: 'PENTHOUSE CO ALARM TO BOSCH DIALER' },
      { loop: 1, address: 167, model: 'CT2', deviceType: 'Supervisory Latching', serialNumber: '4922828803', messages: '2ND FLOOR CO' },
      { loop: 1, address: 168, model: 'CT2', deviceType: 'Supervisory Latching', serialNumber: '4922828810', messages: 'INPUT 2 FOR CO\'S NOT USED' },
      { loop: 1, address: 180, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5221061762', messages: 'PENTHOUSE FIRE SUP TO BOSCH DIALER' },
      { loop: 1, address: 181, model: 'CRR', deviceType: 'Relay Non-Silenceable', serialNumber: '5221663690', messages: 'SOUNDER BASE RELAY' },
      { loop: 1, address: 182, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5216256135', messages: 'DOOR ACCESS RELAY' },
      { loop: 1, address: 183, model: '278', deviceType: 'Pull Station', serialNumber: '4899919535', messages: 'BASEMENT PULL NEXT TO FACP' },
      { loop: 1, address: 185, model: 'CC1S', deviceType: 'Genesis Audible Visible Silence', serialNumber: '5074492140', messages: '1ST FLOOR CC1S POLICE IT CLOSET' },
      { loop: 1, address: 186, model: 'CR', deviceType: 'Relay Non-Silenceable', serialNumber: '5222516872', messages: 'FIRE ROLL UP DOOR' },
      { loop: 1, address: 187, model: 'RM1', deviceType: 'Monitor', serialNumber: '5798621253', messages: 'SOUNDER BASE PWR MONITOR' },
      { loop: 1, address: 188, model: 'CC1S', deviceType: 'Genesis Audible Visible Silence', serialNumber: '5066206359', messages: 'BPS RM F003 NEXT TO FACP' },
      { loop: 1, address: 189, model: 'CC1S', deviceType: 'Genesis Audible Visible Silence', serialNumber: '5066291058', messages: 'FURTHEST FROM PANEL BPS RM F003' },
      { loop: 'N/A', address: 1, model: 'LCD C', deviceType: 'Annunciator', serialNumber: 'N/A', messages: 'MCFARLAND PUBLIC BLD FIRE PANEL NORMAL' },
      { loop: 'N/A', address: 2, model: 'LCD C', deviceType: 'Annunciator', serialNumber: 'N/A', messages: 'MCFARLAND PUBLIC BLD FIRE PANEL NORMAL' },
      { loop: 'N/A', address: 1, model: 'Genesis', deviceType: 'NAC', serialNumber: 'N/A', messages: 'Bell Active' },
      { loop: 'N/A', address: 2, model: 'Genesis', deviceType: 'NAC', serialNumber: 'N/A', messages: 'NAC 2' },
      { loop: 'N/A', address: 3, model: 'Genesis', deviceType: 'NAC', serialNumber: 'N/A', messages: 'NAC 3' },
      { loop: 'N/A', address: 4, model: 'Genesis', deviceType: 'NAC', serialNumber: 'N/A', messages: 'NAC 4' },
    ]
  },
  {
    key: "rock_county_youth_services",
    name: "Rock County Youth Services",
    location: "Fire Alarm Device Inspection",
    devices: [
      { loop: 2, address: 159, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892474956', messages: 'PULL 2ND FL TOP OF STAIRS MECH RM' },
      { loop: 2, address: 381, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892472907', messages: 'PULL 1ST FL BACK RECEIVING DOOER' },
      { loop: 2, address: 168, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892475977', messages: 'PULL 1ST FL W. VESTIBULE' },
      { loop: 2, address: 169, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892472822', messages: 'PULL 1ST FL MAIN ENTRY VESTIBULE' },
      { loop: 2, address: 376, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892475632', messages: '1ST FL REAR VEST. BY RECEIVING' },
      { loop: 2, address: 167, model: 'SIGA-278', deviceType: 'Dual Action Pull Station', serialNumber: '4892475441', messages: 'PULL 1ST FL MECH. ROOM 141 BY FACP' },
      { loop: 2, address: 126, model: 'SIGA-CC1S', deviceType: 'Auto Sync Output Module', serialNumber: '5065318725', messages: 'NAC 1ST FL MECH. ROOM 141 IN BPS' },
      { loop: 2, address: 134, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226915336', messages: 'DAMPER 2ND FL MECH. ROOM CENTER' },
      { loop: 2, address: 152, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226889354', messages: 'DAMPER 1ST FL BY CELL A-10/A-20' },
      { loop: 2, address: 135, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226841932', messages: 'DAMPER 2ND FL MECH. ROOM CENTER' },
      { loop: 2, address: 158, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226889293', messages: 'DAMPER 1ST FL HALL BY CELL D-10' },
      { loop: 2, address: 142, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226899049', messages: 'DAMPER 2ND FL W. HALL' },
      { loop: 2, address: 155, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226840638', messages: 'DAMPER 1ST FL BY CELL C-10/C-20' },
      { loop: 2, address: 139, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226888890', messages: 'DAMPER 1ST FL BY DAY ROOM SHOWER' },
      { loop: 2, address: 132, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226898103', messages: 'DAMPER 2ND FL MECH. ROOM S.E.' },
      { loop: 2, address: 149, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226890008', messages: 'DAMPER 1ST FL N. HOLDING' },
      { loop: 2, address: 156, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5225867704', messages: 'DAMPER 1ST FL BY CELL C-10/C-20' },
      { loop: 2, address: 140, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226881495', messages: 'DAMPER 1ST FL SHOWER B-05' },
      { loop: 2, address: 151, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226841055', messages: 'DAMPER 1ST FL BY CELL A-10/A-20' },
      { loop: 2, address: 146, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226887497', messages: 'DAMPER 2ND FL CENTER HALL' },
      { loop: 2, address: 150, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226841963', messages: 'DAMPER 1ST FL N. HOLDING' },
      { loop: 2, address: 154, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226840270', messages: 'DAMPER 1ST FL BY CELL D-20/D-30' },
      { loop: 2, address: 133, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226889361', messages: 'DAMPER 2ND FL MECH. ROOM S.' },
      { loop: 2, address: 157, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226889347', messages: 'DAMPER 1ST FL HALL BY CELL D-10' },
      { loop: 2, address: 147, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226887527', messages: 'DAMPER 2ND FL CENTER HALL' },
      { loop: 2, address: 145, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226619593', messages: 'DAMPER 2ND FL CENTER HALL' },
      { loop: 2, address: 141, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226898318', messages: 'DAMPER 2ND FL W. HALL' },
      { loop: 2, address: 143, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226898714', messages: 'DAMPER 2ND FL E. HALL' },
      { loop: 2, address: 131, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226890039', messages: 'DAMPER 2ND FL MECH. ROOM N.E.' },
      { loop: 2, address: 136, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226927001', messages: 'DAMPER 2ND FL MECH. ROOM N.' },
      { loop: 2, address: 137, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226870871', messages: 'DAMPER 2ND FL CELL HALL W.' },
      { loop: 2, address: 138, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226888937', messages: 'DAMPER 2ND FL CELL HALL E.' },
      { loop: 2, address: 144, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226898974', messages: 'DAMPER 2ND FL E. HALL' },
      { loop: 2, address: 148, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226888920', messages: 'DAMPER 2ND FL CENTER HALL' },
      { loop: 2, address: 153, model: 'SIGA-CR', deviceType: 'Control Relay Module', serialNumber: '5226888746', messages: 'DAMPER 1ST FL BY CELL D-20/D-30' },
      { loop: 2, address: 377, model: 'SIGA-CT2 ( Circuit 1 )', deviceType: 'Dual Input Module', serialNumber: '4928653546', messages: 'FLOW 1ST FL MECH RM 141' },
      { loop: 2, address: 379, model: 'SIGA-CT2 ( Circuit 1 )', deviceType: 'Dual Input Module', serialNumber: '4928703463', messages: 'DELUGE ALARM 1ST FL MECH RM 141' },
      { loop: 2, address: 378, model: 'SIGA-CT2 ( Circuit 2 )', deviceType: 'Dual Input Module', serialNumber: '4928653553', messages: 'TAMPER 1ST FL MECH RM 141' },
      { loop: 2, address: 380, model: 'SIGA-CT2 ( Circuit 2 )', deviceType: 'Dual Input Module', serialNumber: '4928703470', messages: 'DELUGE TROUBLE 1ST FL MECH RM 141' },
      { loop: 2, address: 127, model: 'SIGA-AA50 ( Channel 1 )', deviceType: '50W Intelligent Audio Amplifier', serialNumber: '5103630529', messages: 'AMP A1 1ST FL MECH. ROOM 141 IN APS' },
      { loop: 2, address: 129, model: 'SIGA-AA50 ( Channel 1 )', deviceType: '50W Intelligent Audio Amplifier', serialNumber: '5103629943', messages: 'AMP A2 1ST FL MECH. ROOM 141 IN APS' },
      { loop: 2, address: 128, model: 'SIGA-AA50 ( Channel 2 )', deviceType: '50W Intelligent Audio Amplifier', serialNumber: '5103630536', messages: 'AMP A1 1ST FL MECH. ROOM 141 IN APS' },
      { loop: 2, address: 130, model: 'SIGA-AA50 ( Channel 2 )', deviceType: '50W Intelligent Audio Amplifier', serialNumber: '5103629950', messages: 'AMP A2 1ST FL MECH. ROOM 141 IN APS' },
      { loop: 2, address: 62, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3832292414', messages: 'HEAT 1ST FL MECH. ROOM 141' },
      { loop: 2, address: 64, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3832292674', messages: 'HEAT 1ST FL SHOWER N.E. DAY ROOM' },
      { loop: 2, address: 63, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831747120', messages: 'HEAT 1ST FL SHOWER ROOM' },
      { loop: 2, address: 59, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831747540', messages: 'HEAT 1ST FL ROOM 145' },
      { loop: 2, address: 36, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831746147', messages: 'HEAT 2ND FL MECH. ROOM E.' },
      { loop: 2, address: 65, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3832293251', messages: 'HEAT 1ST FL SHOWER N.E. DAY ROOM' },
      { loop: 2, address: 61, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831746130', messages: 'HEAT 1ST FL GRNDS EQUIP RM 144 EXT' },
      { loop: 2, address: 37, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831746215', messages: 'HEAT 2ND FL MECH. ROOM W.' },
      { loop: 2, address: 258, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831747106', messages: 'HEAT 1ST FL SERVING KITCHEN RM 136' },
      { loop: 2, address: 60, model: 'SIGA-HRD', deviceType: 'Fixed Temp Heat Detector', serialNumber: '3831749773', messages: 'HEAT 1ST FL GENERATOR RM 142' },
      { loop: 2, address: 257, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981976', messages: 'SMOKE 1ST FL VISITATION RM. 111' },
      { loop: 2, address: 95, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953903589', messages: 'SMOKE 1ST FL BY DAY ROOM E' },
      { loop: 2, address: 9, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327572', messages: 'DUCT SMK 1ST FL BY DAY ROOM SHOWERS' },
      { loop: 2, address: 27, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953914592', messages: 'SMOKE 2ND FL MULTIPURPOSE RM. N.' },
      { loop: 2, address: 21, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325301', messages: 'DUCT SMK 1ST FL BY CELL A-10/A20' },
      { loop: 2, address: 265, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981891', messages: 'SMOKE 1ST FL TOILET RM 113' },
      { loop: 2, address: 6, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326414', messages: 'DUCT SMK 2ND FL MECH. ROOM N.' },
      { loop: 2, address: 32, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922610', messages: 'SMOKE 2ND FL HALL BY STORAGE 204' },
      { loop: 2, address: 275, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981730', messages: 'SMOKE 1ST FL CENTRAL CONTROL S.' },
      { loop: 2, address: 23, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326094', messages: 'DUCT SMK 1ST FL BY CELL D-20/D-30' },
      { loop: 2, address: 279, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921620', messages: 'SMOKE 1ST FL VISITATION RM 130' },
      { loop: 2, address: 125, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921644', messages: 'SMOKE 2ND FL UNIT C STORAGE' },
      { loop: 2, address: 38, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922856', messages: 'SMOKE 1ST FL PATIENT RM 70' },
      { loop: 2, address: 40, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921842', messages: 'SMOKE 2ND FL DAY ROOM BY CELL B-50' },
      { loop: 2, address: 20, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326100', messages: 'DUCT SMK 1ST FL BY CELL A-10/A-20' },
      { loop: 2, address: 48, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921651', messages: 'SMOKE 1ST FL OFFICE RM 107' },
      { loop: 2, address: 2, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326445', messages: 'DUCT SMK 2ND FL MECH. ROOM S.E.' },
      { loop: 2, address: 66, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981099', messages: 'SMOKE 1ST FL SEC./NON SEC. M.P. RM R-03' },
      { loop: 2, address: 119, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953917845', messages: 'SMOKE 1ST FL RESIDENT RM R-30' },
      { loop: 2, address: 68, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922177', messages: 'SMOKE 1ST FL EXAM ROOM' },
      { loop: 2, address: 69, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912109', messages: 'SMOKE 1ST FL CORRIDOR 152' },
      { loop: 2, address: 13, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919328364', messages: 'DUCT SMK 2ND FL E. HALL' },
      { loop: 2, address: 49, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912123', messages: 'SMOKE 1ST FL STAFF TOILET RM 157' },
      { loop: 2, address: 256, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953983437', messages: 'SMOKE 1ST FL VISITATION RM. 110' },
      { loop: 2, address: 264, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923297', messages: 'SMOKE 1ST FL JANITORS CLOSET RM 135' },
      { loop: 2, address: 270, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945698233', messages: 'SMOKE 1ST FL PROGRAM STORAGE RM 119' },
      { loop: 2, address: 282, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945519293', messages: 'SMOKE 1ST FL CORRIDOR 129 N.W.' },
      { loop: 2, address: 269, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3944483519', messages: 'SMOKE 1ST FL PROGRAM STORAGE RM 117' },
      { loop: 2, address: 276, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981037', messages: 'SMOKE 1ST FL CENTRAL CONTROL BY FAAP' },
      { loop: 2, address: 121, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953911836', messages: 'SMOKE 1ST FL OFFICE RM R-60' },
      { loop: 2, address: 8, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325257', messages: 'DUCT SMK 2ND FL CELL HALL E.' },
      { loop: 2, address: 76, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912208', messages: 'SMOKE 1ST FL ELEC. RM. 143' },
      { loop: 2, address: 39, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922962', messages: 'SMOKE 1ST FL OFFICE RM 40' },
      { loop: 2, address: 52, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325639', messages: 'DUCT SMK 1ST FL HALL BY CELL D-10' },
      { loop: 2, address: 10, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327800', messages: 'DUCT SMK 2ND FL W. HALL' },
      { loop: 2, address: 254, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982218', messages: 'SMOKE 1ST FL VISITATION RM. 108' },
      { loop: 2, address: 15, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325646', messages: 'DUCT SMK 2ND FL CENTER HALL' },
      { loop: 2, address: 123, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953980993', messages: 'SMOKE 1ST FL NON-SECURE DAY ROOM R-0' },
      { loop: 2, address: 75, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953911959', messages: 'SMOKE 1ST FL W. VESTIBULE' },
      { loop: 2, address: 272, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945519699', messages: 'SMOKE 1ST FL ELEC. CLOSET IN CENTRAL CTRL' },
      { loop: 2, address: 77, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945515363', messages: 'SMOKE 1ST FL MECH. ROOM 141 ABOVE FACP' },
      { loop: 2, address: 71, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922511', messages: 'SMOKE 1ST FL INTAKE ROOM' },
      { loop: 2, address: 122, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981945', messages: 'SMOKE 1ST FL OFFICE STATION R-09' },
      { loop: 2, address: 70, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982331', messages: 'SMOKE 1ST FL TOILET RM 154' },
      { loop: 2, address: 266, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945312894', messages: 'SMOKE 1ST FL JANITORS CLOSET RM 133' },
      { loop: 2, address: 277, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945516094', messages: 'SMOKE 1ST FL CENTRAL CONTROL W.' },
      { loop: 2, address: 251, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945513802', messages: 'SMOKE 1ST FL SALLYPORT AREA' },
      { loop: 2, address: 262, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981815', messages: 'SMOKE 1ST FL COR. 134 BY JANITOR CLOSET' },
      { loop: 2, address: 16, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919328128', messages: 'DUCT SMK 2ND FL CENTER HALL' },
      { loop: 2, address: 53, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326247', messages: 'DUCT SMK 1ST FL HALL BY CELL D-10' },
      { loop: 2, address: 283, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945541836', messages: 'SMOKE 1ST FL CORRIDOR 129 W.' },
      { loop: 2, address: 47, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912185', messages: 'SMOKE 1ST FL OFFICE RM 105' },
      { loop: 2, address: 5, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325097', messages: 'DUCT SMK 2ND FL MECH. ROOM CENTER' },
      { loop: 2, address: 11, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325561', messages: 'DUCT SMK 2ND FL W. HALL' },
      { loop: 2, address: 263, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922597', messages: 'SMOKE 1ST FL DETENTION SUPPLY RM 137' },
      { loop: 2, address: 28, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921729', messages: 'SMOKE 2ND FL DAY ROOM BY CELL E-20' },
      { loop: 2, address: 117, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912307', messages: 'SMOKE 1ST FL RESIDENT RM R-10' },
      { loop: 2, address: 259, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953983482', messages: 'SMOKE 1ST FL REAR VEST. 135' },
      { loop: 2, address: 288, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945514465', messages: 'SMOKE 1ST FL RESIDENT LAUNDRY' },
      { loop: 2, address: 44, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953914790', messages: 'SMOKE 1ST FL RECEPTION 103' },
      { loop: 2, address: 285, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945712564', messages: 'SMOKE 1ST FL CORRIDOR 129 BY DAY ROOM E' },
      { loop: 2, address: 260, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953981952', messages: 'SMOKE 1ST FL INNER REAR VESTIBULE' },
      { loop: 2, address: 12, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327848', messages: 'DUCT SMK 2ND FL E. HALL' },
      { loop: 2, address: 25, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326360', messages: 'DUCT SMK 1ST FL BY CELL C-10/C-20' },
      { loop: 2, address: 114, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953911614', messages: 'SMOKE 1ST FL RESIDENT RM R-90' },
      { loop: 2, address: 94, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923778', messages: 'SMOKE 1ST FL BY DAY ROOM D' },
      { loop: 2, address: 268, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3934112535', messages: 'SMOKE 1ST FL PROGRAM B RM 116' },
      { loop: 2, address: 91, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3947293276', messages: 'SMOKE 1ST FL ADMIN OFFICE RM 106' },
      { loop: 2, address: 24, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325691', messages: 'DUCT SMK 1ST FL BY CELL C-10/C-20' },
      { loop: 2, address: 50, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945515974', messages: 'SMOKE 2ND FL TOP OF W. STAIRS' },
      { loop: 2, address: 84, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922344', messages: 'SMOKE 1ST FL BY DAY ROOM A' },
      { loop: 2, address: 261, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953984144', messages: 'SMOKE 1ST FL COR. 134 BY STAFF RR' },
      { loop: 2, address: 85, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921569', messages: 'SMOKE 1ST FL BY DAY ROOM B' },
      { loop: 2, address: 45, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982317', messages: 'SMOKE 1ST FL FILE RM 104' },
      { loop: 2, address: 124, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982010', messages: 'SMOKE 1ST FL NON-SECURE DAY ROOM W.' },
      { loop: 2, address: 19, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325707', messages: 'DUCT SMK 1ST FL N. HOLDING' },
      { loop: 2, address: 286, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945541379', messages: 'SMOKE 1ST FL HALL BY S.E. MULTPURPOSE RM' },
      { loop: 2, address: 88, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922801', messages: 'SMOKE 1ST FL FRONT ENTRANCE' },
      { loop: 2, address: 120, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953914820', messages: 'SMOKE 1ST FL RESIDENT ROOM R-50' },
      { loop: 2, address: 82, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921873', messages: 'SMOKE 1ST FL DAY ROOM C-01' },
      { loop: 2, address: 46, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921767', messages: 'SMOKE 1ST FL MULTIPURPOSE RM 156' },
      { loop: 2, address: 22, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327824', messages: 'DUCT SMK 1ST FL BY CELL D-20/D-30' },
      { loop: 2, address: 271, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945515998', messages: 'SMOKE 1ST FL CENTRAL CONTROL E.' },
      { loop: 2, address: 72, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922160', messages: 'SMOKE 1ST FL CLEAN LAUNDRY RM' },
      { loop: 2, address: 4, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919328159', messages: 'DUCT SMK 2ND FL MECH. ROOM CENTER' },
      { loop: 2, address: 252, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945516032', messages: 'SMOKE 1ST FL BY ELEC. ROOM 124' },
      { loop: 2, address: 14, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325585', messages: 'DUCT SMK 2ND FL CENTER HALL' },
      { loop: 2, address: 51, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327664', messages: 'DUCT SMK 1ST FL SHOWER B-05' },
      { loop: 2, address: 33, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923334', messages: 'SMOKE 2ND FL DAY ROOM BY CELL C-50' },
      { loop: 2, address: 18, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919325578', messages: 'DUCT SMK 1ST FL N. HOLDING' },
      { loop: 2, address: 278, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953911737', messages: 'SMOKE 1ST FL VISITATION RM 129' },
      { loop: 2, address: 284, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945519354', messages: 'SMOKE 1ST FL CORRIDOR 129 BY DAY ROOM D' },
      { loop: 2, address: 29, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923006', messages: 'SMOKE 2ND FL DAY ROOM BY CELL D-20' },
      { loop: 2, address: 42, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923105', messages: 'SMOKE 1ST FL PROGRAM STORAGE R-04' },
      { loop: 2, address: 273, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945519347', messages: 'SMOKE 1ST FL EQUIP. RM. IN CENTRAL CTRL N.' },
      { loop: 2, address: 67, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921705', messages: 'SMOKE 1ST FL CORRIDOR 102' },
      { loop: 2, address: 255, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982812', messages: 'SMOKE 1ST FL VISITATION RM. 109' },
      { loop: 2, address: 274, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945514274', messages: 'SMOKE 1ST FL EQUIP. RM. IN CENTRAL CTRL S.' },
      { loop: 2, address: 115, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922153', messages: 'SMOKE 1ST FL RESIDENT RM R-80' },
      { loop: 2, address: 267, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3947250927', messages: 'SMOKE 1ST FL STAFF TOILET RM 123' },
      { loop: 2, address: 26, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912079', messages: 'SMOKE 2ND FL MULTIPURPOSE RM. S.' },
      { loop: 2, address: 41, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953923655', messages: 'SMOKE 2ND FL DAY ROOM BY CELL A-40' },
      { loop: 2, address: 280, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922047', messages: 'SMOKE 1ST FL VISITATION RM 131' },
      { loop: 2, address: 7, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919326537', messages: 'DUCT SMK 2ND FL CELL HALL W.' },
      { loop: 2, address: 289, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922603', messages: 'SMOKE 1ST FL MAINTENANCE OFFICE' },
      { loop: 2, address: 43, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953982256', messages: 'SMOKE 1ST FL JANITORS CLOSET RM 05' },
      { loop: 2, address: 287, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945513772', messages: 'SMOKE 1ST FL VESTIBULE BY RECEIVING' },
      { loop: 2, address: 1, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327640', messages: 'DUCT SMK 2ND FL MECH. ROOM N.E.' },
      { loop: 2, address: 17, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919327947', messages: 'DUCT SMK 2ND FL CENTER HALL' },
      { loop: 2, address: 31, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953912147', messages: 'SMOKE 1ST FL INTAKE AREA' },
      { loop: 2, address: 118, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922641', messages: 'SMOKE 1ST FL RESIDENT RM R-20' },
      { loop: 2, address: 3, model: 'SIGA2-PS', deviceType: 'Photoelectric smoke detector', serialNumber: '3919328722', messages: 'DUCT SMK 2ND FL MECH. ROOM S.' },
      { loop: 2, address: 281, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922931', messages: 'SMOKE 1ST FL VISITATION RM 132' },
      { loop: 2, address: 74, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953921637', messages: 'SMOKE 1ST FL PROPERTY STORAGE RM 148' },
      { loop: 2, address: 253, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3945516193', messages: 'SMOKE 1ST FL EQUIP. ROOM 125' },
      { loop: 2, address: 73, model: 'SIGA-OSD', deviceType: 'Optical Smoke Detector', serialNumber: '3953922672', messages: 'SMOKE 2ND FL ROOM 203 CLOSET' }
    ]
  }
];
